### ISSUE TITLE
指标统计问题

### ISSUE THREAD

**Issue by LetianNing** [wtl52656/MM-STGED#3]
您好，在关于指标统计方面我发现召回率，acc等指标都是统计的还原后的整条轨迹上的情况，但是模型的输入是真实轨迹下采样之后的短轨迹，那在指标统计的时候是不是应该将下采样的短轨迹中所对应点剔除再统计指标呢？这样似乎能够更好的反映出缺失点的还原情况。 还是说任务追求的是整条轨迹的还原情况而并非仅针对于缺失点的还原情况？

**Comment by wtl52656** [comment]
追求的还是整条轨迹的还原情况，其实在输入到模型的时候即使对于已观测点，它也只有经纬度信息是已知的，对应的路段信息也是未知的。对于在评估的时候会对所有轨迹点（已知和未知）的路段进行评估。

**Comment by LetianNing** [comment]
非常感谢您快速的回复。另外我还有一个小问题，我观察到模型的输入为一个三元组(x,y,t)，但我目前尝试替换输入为已观测点的路段ID然后使用嵌入的方式使输入转为(batch_size,seq_len,d_model)，这种把路段ID当做输入是可以的吗，或者使用经纬度的二元组当做输入？

**Comment by wtl52656** [comment]
可以输入路段ID，都是轨迹点的相关特征，不过改完之后还是需要对代码做些小的改动，确保能够跑起来

**Comment by LetianNing** [comment]
万分感谢！

**Comment by LetianNing** [comment]
您好，对于

**Comment by LetianNing** [comment]
您好，我想如果已经观察到的点的路段ID以及rate是可以当作已知的信息输入模型的话，那我把已观测的点替换模型预测的轨迹中相应的点，这种策略是肯定会提升指标的。是否使用这种策略所有对比实验也要使用这种策略来保持一致。还是已经观察到的点的路段ID以及rate是要当未知的。上面的是我个人的一些理解和疑问，如果我有什么理解错误的地方还请您指正，万分感谢。

**Comment by wtl52656** [comment]
已观测点的路段ID和rate我认为是不应该输进入的，因为路段ID和rate是通过道路匹配获得的，而基于隐马尔可夫的道路匹配算法需要使用已观测和未观测的点一块输入到道路匹配的代码中，这样我认为在获得路段ID时就已经将未知点信息引入了，会造成信息泄漏的问题。

**Comment by LetianNing** [comment]
感谢你的解惑，让我有了更深的了解，所以为了规范这个模型的输入还是应该使用经纬度或者是像用经纬度生成的网格坐标x,y吗？
